### ISSUE TITLE
Set and get the due date of a task

### ISSUE THREAD

**Issue by Bapt5** [inbalboa/pymstodo#1]
Hi Is there a way to set and get the due date of a task with pymstodo ??

**Comment by inbalboa** [comment]
> Hi Is there a way to set and get the due date of a task with pymstodo ??

Hi!

Now it's possible.
A Task class property 'due_date' has been added.
Usage example:
```python
...
tasks = todo_client.get_tasks(list_id)
task = tasks[0]
print(f'{task.title} {task.due_date}')
```

And you can pass 'due_date' parameter to the 'create_task' method to create new task with due date:
```python
from datetime import datetime
...
due_date = datetime(2021, 12, 31)
todo_client.create_task(new_task_text, list_id, due_date=due_date)
```

**Comment by Bapt5** [comment]
Ok Thank you very much for this update.

**Comment by Bapt5** [comment]
I have another question. Is it possible to set the description of the task?

**Comment by inbalboa** [comment]
> I have another question. Is it possible to set the description of the task?

You can set the title (brief description). Do you mean something else? I can't find the description field for the task in the To Do interface.

**Comment by Bapt5** [comment]
In the To Do interface the placeholder of the inputfield is "add a note". Do you find this ?![20210404_133428.jpg](https://user-images.githubusercontent.com/63651713/113507416-8c5dad00-954a-11eb-851f-5a3d785287c4.jpg)

**Comment by inbalboa** [comment]
> In the To Do interface the placeholder of the inputfield is "add a note". Do you find this ?![20210404_133428.jpg](https://user-images.githubusercontent.com/63651713/113507416-8c5dad00-954a-11eb-851f-5a3d785287c4.jpg)

Ok. Added this feature. You can set new task body like this:
```python
...
todo_client.create_task(new_task_text, list_id, body_text='task note')
```
Upgrade and check.

**Comment by Bapt5** [comment]
Okay perfect Thank you for your help
