### ISSUE TITLE
can't authorize

### ISSUE THREAD

**Issue by novastar88** [inbalboa/pymstodo#10]
`invalid_request: The provided value for the input parameter 'redirect_uri' is not valid. The expected value is a URI which matches a redirect URI registered for this client application.`

**Comment by amka** [comment]
@novastar88 You should check your Azure app's settings according to the https://github.com/inbalboa/pymstodo/blob/master/GET_KEY.md instructions. Especially look at point 5.

**Comment by inbalboa** [comment]
Hi!

Sorry for ignoring :-)

Yes, you have to specify the redirect URI as @amka mentioned.

I have updated the description of the flow of getting an API key a bit. It should be clearer.
