### ISSUE TITLE
does not work

### ISSUE THREAD

**Issue by wayroq** [inbalboa/pymstodo#9]
I did everything as written in the instructions, but when I go to https://localhost/login/authorized I get the error "Unable to access the site" code "ERR_CONNECTION_REFUSED"
I'm sure that I'm doing something wrong, please tell me what exactly I'm doing wrong, I had no experience with this before

**Comment by bmorgy** [comment]
I have the same issue.  Did you resolve this?

**Comment by inbalboa** [comment]
Hi!

Sorry for ignoring :-)

You don't have to go manually to `https://localhost/login/authorized`. Run the script as in the example in the README (but specify the actual client_id and client_secret), go to the proposed authorization page and you'll be redirected to a page like https://localhost/login/authorized?code=XXXXXXXXXXXXXX&state=XXXXXXXXXXXXXXX. It's OK if you see an error that the page cannot be displayed, just copy the full URL from the browser address bar and paste it back into the input of the running script. When you receive the token, save it, and you will be able to use the client without further authorization.
